spring.application.name=haiilo-supermarket-checkout
# Docker Compose Integration
spring.docker.compose.enabled=true
spring.docker.compose.lifecycle-management=start_and_stop

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.docker.compose.file=backend/compose.yaml

# spring security
spring.security.user.name=admin
spring.security.user.password=supersafeadminpassword

# JWT Configuration
app.jwt.secret=superdupertopsecretpasswordiiibbbrrrlll123789456456totallysafe
app.jwt.expiration=3600000